/**
 * Represents the layout and design configuration response generated by Gemini.
 * These properties are used to conditionally apply styling based on the user's requested "vibe".
 */
export interface VibeResponse {
  colorPalette: string[];
  fontPairing: string;
  layoutStyle: string;
  reasoning: string;
  uiElementName: string;
}

/**
 * Defines a block of learning content (course module) within the curriculum.
 */
export interface CurriculumModule {
  id: string;
  title: string;
  description: string;
  icon: string;
  duration: string;
}

/**
 * Represents the main navigation states / tabs of the overall application.
 */
export enum AppState {
  HOME = 'HOME',
  NEW_TO_VIBE = 'NEW_TO_VIBE',
  WHAT_IS_WEB_APP = 'WHAT_IS_WEB_APP',
  BUILD_WORKFLOW = 'BUILD_WORKFLOW'
}
